version: "3.9"

services:
  youtufy-db:
    image: postgres:15
    container_name: youtufy-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - youtufy-net

  youtufy-app:
    build: .
    container_name: youtufy-app
    restart: unless-stopped
    depends_on:
      - youtufy-db
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - youtufy-net

volumes:
  pgdata:

networks:
  youtufy-net:
    driver: bridge

